# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Robot test

on: [push]

jobs:
  robot_framework_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Robot Framework dependencies
        run: pip install robotframework-requests robotframework-browser

      - name: Run Robot Framework tests
        run: echo $(robot --version)

      - name: Run Robot Framework tests
        run: robot tests/main.robot
